import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { Bot, Check, Clock3, ExternalLink, Gavel, RefreshCw, ShieldAlert, ShieldCheck, Sparkles, X } from "lucide-react";

type Data = {
  settings: { enabled: boolean; targetAutonomyPercent: number; minimumConfidence: number; approvalActions: string[] };
  decisions: Array<{ id: number; actionType: string; recommendation: string; reasoning: string; evidence?: string | null; model?: string | null; riskLevel?: string | null; confidence: number; status: string }>;
  regulatorySources: Array<{ id: number; name: string; url: string; jurisdiction: string; lastCheckedAt?: string | null }>;
  summary: { pendingApprovals: number; automaticallyCleared: number; pendingLegalReviews: number };
};
const labels: Record<string, string> = { tax_submission: "Skatteindberetning", vat_submission: "Momsindberetning", payment: "Betaling", payroll_submission: "Lønindberetning", period_close: "Periodelukning", annual_report: "Årsrapport", audit_statement: "Revisorerklæring", credit_note: "Kreditnota", legal_rule_change: "Aktivering af lovændring", user_access: "Ændring af adgang", data_deletion: "Sletning af data" };

export default function AiStyring({ companyId }: { companyId: number }) {
  const qc = useQueryClient();
  const { user, isPlatformAdmin } = useAuth();
  const key = ["/api/ai-governance", companyId] as const;
  const query = useQuery<Data>({ queryKey: key, queryFn: async () => (await apiRequest("GET", `/api/ai-governance?companyId=${companyId}`)).json(), refetchInterval: 60_000 });
  const update = useMutation({ mutationFn: async (body: unknown) => (await apiRequest("PATCH", `/api/ai-governance/settings?companyId=${companyId}`, body)).json(), onSuccess: () => qc.invalidateQueries({ queryKey: key }) });
  const decide = useMutation({ mutationFn: async ({ id, action }: { id: number; action: string }) => (await apiRequest("POST", `/api/ai-governance/decisions/${id}/${action}?companyId=${companyId}`, {})).json(), onSuccess: () => qc.invalidateQueries({ queryKey: key }) });
  const monitor = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/regulatory-monitor/run", {})).json(), onSuccess: () => qc.invalidateQueries({ queryKey: key }) });
  if (!query.data) return <Skeleton className="h-[520px] w-full" />;
  const data = query.data;
  const pending = data.decisions.filter((x) => x.status === "afventer_godkendelse");
  return <div className="space-y-5" data-testid="ai-governance-center">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Bot className="h-6 w-6 text-violet-600" /><h2 className="text-xl font-semibold">AI-styring</h2></div><p className="mt-1 text-sm text-muted-foreground">Autopilot med faste godkendelsesporte og komplet beslutningsspor.</p></div><div className="flex items-center gap-2 rounded-lg border bg-card px-3 py-2"><span className="text-sm font-medium">Autopilot</span><Switch checked={data.settings.enabled} onCheckedChange={(enabled) => update.mutate({ enabled })} disabled={!isPlatformAdmin && user?.role !== "leder"} /></div></div>
    <section className="grid gap-4 rounded-xl border bg-card p-5 lg:grid-cols-[210px_1fr]"><div className="lg:border-r lg:pr-5"><p className="text-xs uppercase text-muted-foreground">Målsat autonomi</p><p className="text-5xl font-bold text-violet-600">{data.settings.targetAutonomyPercent}%</p><p className="mt-2 text-xs text-muted-foreground">Kun ved mindst {(data.settings.minimumConfidence * 100).toFixed(0)} % sikkerhed og evidens.</p></div><div><Progress value={data.settings.targetAutonomyPercent} className="h-2.5" /><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat icon={<Clock3 />} label="Afventer menneske" value={data.summary.pendingApprovals} /><Stat icon={<Sparkles />} label="Klar til automatik" value={data.summary.automaticallyCleared} /><Stat icon={<Gavel />} label="Lovændringer" value={data.summary.pendingLegalReviews} /></div></div></section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-xl border bg-card"><div className="border-b px-4 py-3"><h3 className="font-semibold">Obligatorisk godkendelse</h3><p className="text-xs text-muted-foreground">Disse handlinger må AI aldrig gennemføre alene.</p></div><div className="grid gap-2 p-3 sm:grid-cols-2">{data.settings.approvalActions.map((action) => <div key={action} className="flex items-center gap-2 rounded-md border px-3 py-2 text-xs"><ShieldCheck className="h-4 w-4 text-emerald-600" />{labels[action] ?? action}</div>)}</div></section>
      <section className="rounded-xl border bg-card"><div className="border-b px-4 py-3"><h3 className="font-semibold">Godkendelseskø</h3></div><div className="max-h-96 space-y-2 overflow-auto p-3">{pending.length === 0 ? <p className="p-3 text-sm text-muted-foreground">Ingen forslag afventer.</p> : pending.map((item) => { let evidence: string[] = []; try { const parsed = JSON.parse(item.evidence || "[]"); evidence = Array.isArray(parsed) ? parsed.map(String) : []; } catch {} return <div key={item.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><p className="text-sm font-semibold">{labels[item.actionType] ?? item.actionType}</p><div className="flex gap-1"><span className="badge-soft badge-soft-amber">{item.riskLevel || "lav"} risiko</span><span className="badge-soft badge-soft-blue">{Math.round(item.confidence * 100)} %</span></div></div><p className="mt-2 text-xs font-medium">{item.recommendation}</p><p className="mt-1 text-[11px] text-muted-foreground">Begrundelse: {item.reasoning}</p><div className="mt-2 rounded bg-muted/50 p-2 text-[11px]"><span className="font-medium">Dokumentation:</span> {evidence.length ? evidence.join(" · ") : "Ingen dokumentation vedlagt"}{item.model ? ` · Model: ${item.model}` : ""}</div><div className="mt-3 flex gap-2"><Button size="sm" disabled={decide.isPending} onClick={() => decide.mutate({ id: item.id, action: "approve" })}><Check className="mr-1 h-3.5 w-3.5" />Godkend</Button><Button size="sm" variant="outline" disabled={decide.isPending} onClick={() => decide.mutate({ id: item.id, action: "reject" })}><X className="mr-1 h-3.5 w-3.5" />Afvis</Button></div></div>; })}</div></section></div>
    <section className="rounded-xl border bg-card"><div className="flex justify-between gap-3 border-b px-4 py-3"><div><h3 className="font-semibold">Automatisk regelovervågning</h3><p className="text-xs text-muted-foreground">Officielle kilder kontrolleres dagligt; ændringer kræver fagligt review.</p></div>{isPlatformAdmin && <Button size="sm" variant="outline" onClick={() => monitor.mutate()}><RefreshCw className={`mr-2 h-4 w-4 ${monitor.isPending ? "animate-spin" : ""}`} />Kontrollér nu</Button>}</div><div className="divide-y">{data.regulatorySources.map((source) => <div key={source.id} className="flex flex-wrap items-center justify-between gap-2 px-4 py-3"><div><p className="text-sm font-medium">{source.name}</p><p className="text-xs text-muted-foreground">{source.jurisdiction} · {source.lastCheckedAt ? new Date(source.lastCheckedAt).toLocaleString("da-DK") : "Første kontrol afventer"}</p></div><a href={source.url} target="_blank" rel="noreferrer" className="flex items-center text-xs text-primary">Officiel kilde <ExternalLink className="ml-1 h-3.5 w-3.5" /></a></div>)}</div></section>
    <div className="flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/25"><ShieldAlert className="h-5 w-5 shrink-0" /><div><p className="text-sm font-semibold">AI er regnskabsassistent — ikke godkendt revisor</p><p className="text-xs text-muted-foreground">Lovpligtige erklæringer og nye juridiske fortolkninger kræver en ansvarlig person med rette kompetence.</p></div></div>
  </div>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-lg border p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{label}</div><p className="mt-1 text-xl font-semibold">{value}</p></div>; }
