import { useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Skeleton } from "@/components/ui/skeleton";
import { CheckCircle2, Circle, HelpCircle, Plug, Rocket } from "lucide-react";

type Onboarding = { completed: number; total: number; percent: number; readyForPilot: boolean; steps: Array<{ id: string; title: string; complete: boolean; action: string }> };
type Adapter = { id: string; name: string; mode: string; configured: boolean };
type Article = { slug: string; category: string; title: string; steps: string[] };
type Plan = { id: number; name: string; priceMonthly?: number; monthlyPrice?: number; description?: string };

export default function Driftsklarhed() {
  const onboarding = useQuery<Onboarding>({ queryKey: ["/api/onboarding/status"], queryFn: async () => (await apiRequest("GET", "/api/onboarding/status")).json() });
  const adapters = useQuery<{ adapters: Adapter[] }>({ queryKey: ["/api/integration-adapters/status"], queryFn: async () => (await apiRequest("GET", "/api/integration-adapters/status")).json() });
  const help = useQuery<{ articles: Article[] }>({ queryKey: ["/api/support/knowledge"], queryFn: async () => (await apiRequest("GET", "/api/support/knowledge")).json() });
  const plans = useQuery<Plan[]>({ queryKey: ["/api/plans"], queryFn: async () => { const value = await (await apiRequest("GET", "/api/plans")).json(); return Array.isArray(value) ? value : value.plans || []; } });
  if (onboarding.isLoading) return <Skeleton className="h-72 w-full" />;
  return <div className="space-y-5">
    <div><h2 className="text-xl font-semibold tracking-tight">Driftsklarhed og onboarding</h2><p className="text-sm text-muted-foreground">Én samlet kontrol af opsætning, integrationer, support og abonnement.</p></div>
    {onboarding.data && <section className="rounded-md border p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Rocket className="h-5 w-5 text-emerald-600" /><div><div className="font-medium">Onboarding: {onboarding.data.percent}%</div><div className="text-xs text-muted-foreground">{onboarding.data.completed} af {onboarding.data.total} kontroller gennemført</div></div></div><span className={`badge-soft ${onboarding.data.readyForPilot ? "badge-soft-green" : "badge-soft-amber"}`}>{onboarding.data.readyForPilot ? "Klar til pilot" : "Handling mangler"}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{onboarding.data.steps.map((step) => <div key={step.id} className="flex gap-2 rounded-md bg-muted/40 p-3">{step.complete ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" /> : <Circle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />}<div><div className="text-sm font-medium">{step.title}</div><div className="text-xs text-muted-foreground">{step.complete ? "Gennemført" : step.action}</div></div></div>)}</div></section>}
    <section className="rounded-md border p-4"><div className="mb-3 flex items-center gap-2 font-medium"><Plug className="h-4 w-4" /> Integrationsadaptere</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(adapters.data?.adapters || []).map((adapter) => <div key={adapter.id} className="flex items-center justify-between rounded-md bg-muted/40 p-3"><div><div className="text-sm font-medium">{adapter.name}</div><div className="text-xs text-muted-foreground">{adapter.mode}</div></div><span className={`badge-soft ${adapter.configured ? "badge-soft-green" : "badge-soft-amber"}`}>{adapter.configured ? "Klar" : "Kræver opsætning"}</span></div>)}</div></section>
    <section className="rounded-md border p-4"><div className="mb-3 flex items-center gap-2 font-medium"><HelpCircle className="h-4 w-4" /> Hjælpecenter</div><div className="grid gap-3 md:grid-cols-2">{(help.data?.articles || []).map((article) => <details key={article.slug} className="rounded-md border p-3"><summary className="cursor-pointer text-sm font-medium">{article.title} <span className="ml-1 text-xs font-normal text-muted-foreground">· {article.category}</span></summary><ol className="mt-2 list-decimal space-y-1 pl-5 text-xs text-muted-foreground">{article.steps.map((step) => <li key={step}>{step}</li>)}</ol></details>)}</div></section>
    <section className="rounded-md border p-4"><div className="mb-3 font-medium">Abonnementer og prøveperiode</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(plans.data || []).map((plan) => <div key={plan.id} className="rounded-md bg-muted/40 p-3"><div className="font-medium">{plan.name}</div><div className="mt-1 text-lg font-semibold">{Number(plan.priceMonthly ?? plan.monthlyPrice ?? 0).toLocaleString("da-DK")} kr./md.</div><div className="mt-1 text-xs text-muted-foreground">{plan.description || "Abonnement kan prøves før aktivering."}</div></div>)}</div><p className="mt-3 text-xs text-muted-foreground">Betaling aktiveres ikke automatisk. En prøveperiode og et abonnement kræver virksomhedens udtrykkelige valg.</p></section>
  </div>;
}
