import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/auth";
import { useCustomers, useEmployees } from "@/App";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest, openAuthedFile, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { CheckCircle2, Download, FileText, Lock, Plus, ShieldCheck, Trash2 } from "lucide-react";
import type { Consent, Customer, DataRequest, Employee } from "@shared/schema";
import { PageHeader, SectionCard } from "@/components/premium";

type GDPRData = {
  retention: { timeEntries: number; gps: number; absences: number; photos: number };
  defaults: { gps: { maaneder: number }; tidsregistreringer: { maaneder: number }; fravaer: { maaneder: number }; fotos: { maaneder: number } };
  dpaAcceptedAt: string | null; dpaAcceptedBy: string | null;
  requests: DataRequest[]; consents: Consent[]; lagring: string;
};
type Person = { id: number; name: string };
const KIND: Record<string, string> = { indsigt: "Indsigt", sletning: "Sletning", portabilitet: "Dataportabilitet" };
const CONSENT: Record<string, string> = { gps: "GPS-sporing", foto: "Fotodokumentation", databehandling: "Databehandling" };
function date(value?: string | null) { return value ? new Intl.DateTimeFormat("da-DK", { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)) : "—"; }

export default function Gdpr() {
  const { user, companyId } = useAuth(); const { toast } = useToast();
  const canManage = user?.role === "leder" || user?.role === "platform_admin";
  const { data, isLoading } = useQuery<GDPRData>({ queryKey: ["/api/gdpr", companyId], queryFn: async () => (await apiRequest("GET", "/api/gdpr")).json(), enabled: canManage });
  const { data: employees = [] } = useEmployees(companyId);
  const { data: customers = [] } = useCustomers(companyId);
  const { data: users = [] } = useQuery<Person[]>({ queryKey: ["/api/users", companyId], queryFn: async () => (await apiRequest("GET", "/api/users")).json(), enabled: canManage });
  const [retention, setRetention] = useState(data?.retention);
  const [dpaOpen, setDpaOpen] = useState(false); const [privacy, setPrivacy] = useState(false);
  const [requestOpen, setRequestOpen] = useState(false); const [exportOpen, setExportOpen] = useState(false);
  const [cleanupConfirm, setCleanupConfirm] = useState(false); const [cleanupResult, setCleanupResult] = useState<Record<string, unknown> | null>(null);
  const [deleteRequest, setDeleteRequest] = useState<DataRequest | null>(null); const [processResult, setProcessResult] = useState<Record<string, unknown> | null>(null);
  useEffect(() => setRetention(data?.retention), [data?.retention]);
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["/api/gdpr"] });
  const saveRetention = useMutation({ mutationFn: async () => (await apiRequest("PATCH", "/api/gdpr/opbevaring", retention)).json(), onSuccess: () => { invalidate(); toast({ title: "Opbevaringspolitik er gemt" }); }, onError: (e: Error) => toast({ title: "Kunne ikke gemme", description: e.message, variant: "destructive" }) });
  const cleanup = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/gdpr/oprydning")).json(), onSuccess: (result) => { invalidate(); setCleanupConfirm(false); setCleanupResult(result); }, onError: (e: Error) => toast({ title: "Oprydning mislykkedes", description: e.message, variant: "destructive" }) });
  const acceptDpa = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/gdpr/databehandleraftale")).json(), onSuccess: () => { invalidate(); setDpaOpen(false); toast({ title: "Databehandleraftalen er accepteret" }); }, onError: (e: Error) => toast({ title: "Kunne ikke acceptere aftalen", description: e.message, variant: "destructive" }) });
  const process = useMutation({ mutationFn: async (id: number) => (await apiRequest("POST", `/api/gdpr/anmodning/${id}/behandl`)).json(), onSuccess: (result) => { invalidate(); setDeleteRequest(null); setProcessResult(result.resultat ?? result); toast({ title: "Anmodningen er behandlet" }); }, onError: (e: Error) => toast({ title: "Kunne ikke behandle anmodningen", description: e.message, variant: "destructive" }) });
  if (!canManage) return <AccessDenied />;
  if (isLoading || !data || !retention) return <Loading />;
  const recommended = { timeEntries: data.defaults.tidsregistreringer.maaneder, gps: data.defaults.gps.maaneder, absences: data.defaults.fravaer.maaneder, photos: data.defaults.fotos.maaneder };
  const consentName = (id: number) => employees.find((employee) => employee.id === id)?.name ?? `Ansat #${id}`;
  return <div className="p-3 md:p-4 space-y-3 max-w-6xl mx-auto">
    <PageHeader eyebrow="Compliance" title="GDPR" description="GDPR og databeskyttelse" />
    <SectionCard data-testid="card-retention" icon={<ShieldCheck className="w-4 h-4" />} className="space-y-3"><div><h2 className="font-medium text-xs">Opbevaringspolitik</h2><p className="text-[11px] text-muted-foreground mt-1">Angiv måneder fra 0 til 240. 0 = gem for altid.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Retention label="Tidsregistreringer" field="timeEntries" value={retention.timeEntries} recommended={recommended.timeEntries} setValue={(value) => setRetention({ ...retention, timeEntries: value })} /><Retention label="GPS-positioner" field="gps" value={retention.gps} recommended={recommended.gps} setValue={(value) => setRetention({ ...retention, gps: value })} /><Retention label="Fraværsregistreringer" field="absences" value={retention.absences} recommended={recommended.absences} setValue={(value) => setRetention({ ...retention, absences: value })} /><Retention label="Fotos og bilag" field="photos" value={retention.photos} recommended={recommended.photos} setValue={(value) => setRetention({ ...retention, photos: value })} /></div><div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" data-testid="button-retention-defaults" onClick={() => setRetention(recommended)}>Brug anbefalede</Button><Button size="sm" data-testid="button-save-retention" disabled={saveRetention.isPending} onClick={() => saveRetention.mutate()}>{saveRetention.isPending ? "Gemmer..." : "Gem politik"}</Button><Button size="sm" variant="destructive" data-testid="button-run-cleanup" onClick={() => setCleanupConfirm(true)}><Trash2 className="w-4 h-4 mr-1" />Kør oprydning nu</Button></div></SectionCard>
    <SectionCard data-testid="card-dpa" className={`p-3 ${data.dpaAcceptedAt ? "border-emerald-500/30 bg-emerald-500/5" : ""}`}><div className="flex items-start justify-between gap-3 flex-wrap"><div className="flex gap-2"><ShieldCheck className={`w-4 h-4 shrink-0 ${data.dpaAcceptedAt ? "text-emerald-600" : "text-muted-foreground"}`} /><div><h2 className="font-medium text-xs">Databehandleraftale</h2>{data.dpaAcceptedAt ? <p className="text-xs text-emerald-800 dark:text-emerald-300 mt-1">Accepteret den {date(data.dpaAcceptedAt)} af {data.dpaAcceptedBy ?? "—"}.</p> : <p className="text-[11px] text-muted-foreground mt-1">Aftalen skal accepteres, før I tager behandling af personoplysninger i brug.</p>}</div></div>{!data.dpaAcceptedAt && <Button size="sm" data-testid="button-open-dpa" onClick={() => setDpaOpen(true)}>Læs og accepter</Button>}</div></SectionCard>
    <SectionCard data-testid="card-requests" icon={<ShieldCheck className="w-4 h-4" />} action={<div className="flex gap-2"><Button size="sm" variant="outline" data-testid="button-open-export" onClick={() => setExportOpen(true)}><Download className="w-4 h-4 mr-1" />Hent udlevering</Button><Button size="sm" data-testid="button-new-request" onClick={() => setRequestOpen(true)}><Plus className="w-4 h-4 mr-1" />Ny anmodning</Button></div>} className="space-y-3"><div><h2 className="font-medium text-xs">Anmodninger</h2><p className="text-[11px] text-muted-foreground mt-1">Indsigt, sletning og dataportabilitet.</p></div>{data.requests.length === 0 ? <p className="text-xs text-muted-foreground py-3" data-testid="empty-requests">Der er ingen registrerede anmodninger.</p> : <div className="space-y-2">{data.requests.map((request) => <div key={request.id} className="rounded-md border border-border/50 p-3 flex gap-2 flex-wrap items-center" data-testid={`row-request-${request.id}`}><div className="min-w-0 flex-1"><div className="flex gap-2 flex-wrap items-center"><span className="font-medium text-xs">{request.subjectName}</span><span className="text-[11px] rounded-full bg-muted px-2 py-0.5">{KIND[request.kind] ?? request.kind}</span><span className={`text-[11px] rounded-full px-2 py-0.5 ${request.status === "behandlet" ? "badge-soft badge-soft-green" : "badge-soft badge-soft-amber"}`}>{request.status === "behandlet" ? "Behandlet" : "Modtaget"}</span></div><p className="text-[11px] text-muted-foreground mt-1">Bedt af {request.requestedBy ?? "—"} · {date(request.createdAt)}{request.note ? ` · ${request.note}` : ""}</p></div>{request.status !== "behandlet" && <Button size="sm" variant="outline" data-testid={`button-process-request-${request.id}`} disabled={process.isPending} onClick={() => request.kind === "sletning" ? setDeleteRequest(request) : process.mutate(request.id)}>Behandl</Button>}</div>)}</div>}</SectionCard>
    <SectionCard data-testid="card-consents" title="Samtykker" icon={<ShieldCheck className="w-4 h-4" />} className="space-y-3">{data.consents.length === 0 ? <p className="text-xs text-muted-foreground py-2" data-testid="empty-consents">Der er endnu ingen registrerede samtykker.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[540px] text-xs"><thead><tr className="border-b border-border text-left text-[11px] text-muted-foreground"><th className="py-2 font-medium">Ansat</th><th className="py-2 font-medium">Type</th><th className="py-2 font-medium">Status</th><th className="py-2 font-medium">Dato</th></tr></thead><tbody>{data.consents.map((consent) => <tr key={consent.id} className="divide-y divide-border/50" data-testid={`row-consent-${consent.id}`}><td className="py-2">{consentName(consent.employeeId)}</td><td className="py-2">{CONSENT[consent.kind] ?? consent.kind}</td><td className={`py-2 ${consent.granted === 1 ? "text-emerald-700 dark:text-emerald-400" : "text-muted-foreground"}`}>{consent.granted === 1 ? "Givet" : "Trukket"}</td><td className="py-2 text-[11px] text-muted-foreground">{date(consent.granted === 1 ? consent.grantedAt : consent.withdrawnAt)}</td></tr>)}</tbody></table></div>}</SectionCard>
    <SectionCard data-testid="card-storage" className="flex gap-2 items-start"><FileText className="w-4 h-4 shrink-0 mt-0.5 text-muted-foreground" /><p className="text-xs text-muted-foreground">Filbackend: <span className="font-medium text-foreground">{data.lagring}</span>. Filer gemmes i den valgte backend og følger opbevaringspolitikken.</p></SectionCard>
    <DpaDialog open={dpaOpen} onOpenChange={setDpaOpen} privacy={privacy} setPrivacy={setPrivacy} accept={() => acceptDpa.mutate()} pending={acceptDpa.isPending} />
    <RequestDialog open={requestOpen} onOpenChange={setRequestOpen} employees={employees} customers={customers} users={users} onSaved={invalidate} />
    <ExportDialog open={exportOpen} onOpenChange={setExportOpen} employees={employees} customers={customers} users={users} />
    <AlertDialog open={cleanupConfirm} onOpenChange={setCleanupConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Kør permanent oprydning?</AlertDialogTitle><AlertDialogDescription>Data, der er ældre end jeres opbevaringspolitik, slettes permanent. Handlingen kan ikke fortrydes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-cleanup">Annuller</AlertDialogCancel><AlertDialogAction data-testid="button-confirm-cleanup" className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => cleanup.mutate()}>Slet nu</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <ResultDialog title="Oprydning gennemført" open={Boolean(cleanupResult)} onOpenChange={() => setCleanupResult(null)} result={cleanupResult} />
    <AlertDialog open={Boolean(deleteRequest)} onOpenChange={(open) => !open && setDeleteRequest(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Anonymisér oplysninger permanent?</AlertDialogTitle><AlertDialogDescription>Personoplysninger anonymiseres permanent. Fakturagrundlag beholdes, som bogføringsloven kræver.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-delete-request">Annuller</AlertDialogCancel><AlertDialogAction data-testid="button-confirm-delete-request" className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => deleteRequest && process.mutate(deleteRequest.id)}>Anonymisér permanent</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <ResultDialog title="Anmodning behandlet" open={Boolean(processResult)} onOpenChange={() => setProcessResult(null)} result={processResult} />
  </div>;
}
function Retention({ label, field, value, recommended, setValue }: { label: string; field: string; value: number; recommended: number; setValue: (value: number) => void }) { return <div className="space-y-1.5 min-w-0"><Label htmlFor={`retention-${field}`}>{label}</Label><Input id={`retention-${field}`} type="number" min="0" max="240" value={value} onChange={(event) => setValue(Math.min(240, Math.max(0, Number(event.target.value))))} data-testid={`input-retention-${field}`} /><p className="text-xs text-muted-foreground">0 = gem for altid · Anbefalet: {recommended} mdr.</p></div>; }
function AccessDenied() { return <div className="p-3 md:p-4 max-w-2xl mx-auto"><div className="rounded-md border border-border/50 bg-card p-4 text-center" data-testid="card-gdpr-access"><Lock className="w-8 h-8 text-muted-foreground mx-auto mb-3" /><p className="text-xs text-muted-foreground">Kun virksomhedens leder kan se GDPR og datapolitik.</p></div></div>; }
function Loading() { return <div className="p-3 md:p-4 space-y-3"><Skeleton className="w-52 h-8" /><Skeleton className="h-64 rounded-md" /><Skeleton className="h-40 rounded-md" /></div>; }
function ResultDialog({ title, open, onOpenChange, result }: { title: string; open: boolean; onOpenChange: (open: boolean) => void; result: Record<string, unknown> | null }) { const labels: Record<string, string> = { gpsStripped: "Fjernede GPS-positioner", timeEntriesDeleted: "Slettede tidsregistreringer", absencesDeleted: "Slettede fraværsposter", photosDeleted: "Slettede fotos" }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><div className="space-y-2" data-testid="text-cleanup-result">{Object.entries(result ?? {}).filter(([key]) => key !== "perCompany").map(([key, value]) => <p className="text-sm" key={key}><span className="text-muted-foreground">{labels[key] ?? key}: </span><span className="font-medium">{typeof value === "object" ? JSON.stringify(value) : String(value)}</span></p>)}</div><Button onClick={() => onOpenChange(false)} data-testid="button-close-result">Luk</Button></DialogContent></Dialog>; }
function DpaDialog({ open, onOpenChange, privacy, setPrivacy, accept, pending }: { open: boolean; onOpenChange: (open: boolean) => void; privacy: boolean; setPrivacy: (value: boolean) => void; accept: () => void; pending: boolean }) { const { data } = useQuery<{ tekst: string; privatliv: string }>({ queryKey: ["/api/gdpr/databehandleraftale/tekst"], queryFn: async () => (await apiRequest("GET", "/api/gdpr/databehandleraftale/tekst")).json(), enabled: open }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{privacy ? "Privatlivspolitik" : "Databehandleraftale"}</DialogTitle></DialogHeader><div className="max-h-[60vh] overflow-y-auto whitespace-pre-wrap text-sm border rounded-lg p-3" data-testid="text-dpa">{privacy ? data?.privatliv ?? "Indlæser..." : data?.tekst ?? "Indlæser..."}</div><div className="flex justify-between gap-2 flex-wrap"><Button variant="outline" data-testid="button-toggle-privacy" onClick={() => setPrivacy(!privacy)}>{privacy ? "Læs databehandleraftalen" : "Læs privatlivspolitikken"}</Button>{!privacy && <Button data-testid="button-accept-dpa" disabled={pending || !data} onClick={accept}>{pending ? "Accepterer..." : "Accepter"}</Button>}</div></DialogContent></Dialog>; }
function SubjectSelect({ subjectType, subjectId, setSubjectType, setSubjectId, employees, customers, users }: { subjectType: string; subjectId: string; setSubjectType: (value: string) => void; setSubjectId: (value: string) => void; employees: Employee[]; customers: Customer[]; users: Person[] }) { const rows = subjectType === "ansat" ? employees : subjectType === "kunde" ? customers : users; return <><div className="space-y-1.5"><Label>Person-type</Label><Select value={subjectType} onValueChange={(value) => { setSubjectType(value); setSubjectId(""); }}><SelectTrigger data-testid="select-subject-type"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ansat">Ansat</SelectItem><SelectItem value="kunde">Kunde</SelectItem><SelectItem value="bruger">Bruger</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>Person</Label><Select value={subjectId} onValueChange={setSubjectId}><SelectTrigger data-testid="select-subject"><SelectValue placeholder="Vælg person" /></SelectTrigger><SelectContent>{rows.map((row) => <SelectItem key={row.id} value={String(row.id)}>{row.name}</SelectItem>)}</SelectContent></Select></div></>; }
function RequestDialog({ open, onOpenChange, employees, customers, users, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; employees: Employee[]; customers: Customer[]; users: Person[]; onSaved: () => void }) { const { toast } = useToast(); const [kind, setKind] = useState("indsigt"); const [subjectType, setSubjectType] = useState("ansat"); const [subjectId, setSubjectId] = useState(""); const [note, setNote] = useState(""); const create = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/gdpr/anmodning", { kind, subjectType, subjectId: Number(subjectId), note: note.trim() || null })).json(), onSuccess: () => { onSaved(); onOpenChange(false); toast({ title: "Anmodningen er registreret" }); }, onError: (e: Error) => toast({ title: "Kunne ikke oprette anmodning", description: e.message, variant: "destructive" }) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Ny GDPR-anmodning</DialogTitle></DialogHeader><div className="space-y-3"><div className="space-y-1.5"><Label>Type</Label><Select value={kind} onValueChange={setKind}><SelectTrigger data-testid="select-request-kind"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="indsigt">Indsigt</SelectItem><SelectItem value="sletning">Sletning</SelectItem><SelectItem value="portabilitet">Dataportabilitet</SelectItem></SelectContent></Select></div><SubjectSelect {...{ subjectType, subjectId, setSubjectType, setSubjectId, employees, customers, users }} /><div className="space-y-1.5"><Label htmlFor="request-note">Note</Label><Textarea id="request-note" value={note} onChange={(event) => setNote(event.target.value)} data-testid="input-request-note" /></div><Button className="w-full" disabled={!subjectId || create.isPending} data-testid="button-save-request" onClick={() => create.mutate()}>{create.isPending ? "Gemmer..." : "Registrér anmodning"}</Button></div></DialogContent></Dialog>; }
function ExportDialog({ open, onOpenChange, employees, customers, users }: { open: boolean; onOpenChange: (open: boolean) => void; employees: Employee[]; customers: Customer[]; users: Person[] }) { const [subjectType, setSubjectType] = useState("ansat"); const [subjectId, setSubjectId] = useState(""); const [format, setFormat] = useState("json"); const { toast } = useToast(); const download = async () => { try { await openAuthedFile(`/api/gdpr/udlevering?subjectType=${encodeURIComponent(subjectType)}&subjectId=${encodeURIComponent(subjectId)}&format=${format}`); } catch (e) { toast({ title: "Kunne ikke hente udleveringen", description: e instanceof Error ? e.message : "Ukendt fejl", variant: "destructive" }); } }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Hent dataudlevering</DialogTitle></DialogHeader><div className="space-y-3"><SubjectSelect {...{ subjectType, subjectId, setSubjectType, setSubjectId, employees, customers, users }} /><div className="space-y-1.5"><Label>Format</Label><Select value={format} onValueChange={setFormat}><SelectTrigger data-testid="select-export-format"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="json">JSON</SelectItem><SelectItem value="csv">CSV</SelectItem></SelectContent></Select></div><Button className="w-full" disabled={!subjectId} data-testid="button-download-export" onClick={download}><Download className="w-4 h-4 mr-1" />Hent udlevering</Button></div></DialogContent></Dialog>; }
